kind: ServiceAccount
apiVersion: v1
metadata:
  name: acorn-system
  namespace: acorn-system

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: acorn-controller
  namespace: acorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acorn-controller
  template:
    metadata:
      labels:
        app: acorn-controller
    spec:
      containers:
        - name: acorn-controller
          image: ghcr.io/acorn-io/acorn
          args:
            - controller
          securityContext:
            runAsUser: 1000
      serviceAccountName: acorn-system
---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: acorn-controller
  namespace: acorn-system
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app: acorn-controller
