node-name: acorn-node
disable: 
  - metrics-server
  - servicelb
  - local-storage
  - traefik
  - coredns
  - runtimes
disable-cloud-controller: true
disable-network-policy: true
disable-helm-controller: true
disable-scheduler: true
kube-apiserver-arg:
  - enable-priority-and-fairness=false
  - feature-gates=AllBeta=false
  - feature-gates=AllAlpha=false
  - watch-cache=false
  - contention-profiling=false
  - profiling=true
  - runtime-config=api/beta=false
  - runtime-config=api/alpha=false
  - disable-admission-plugins=CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota
  - log-flush-frequency=25s
kube-controller-manager-arg:
  - profiling=false
  - log-flush-frequency=25s
  - feature-gates=AllAlpha=false
  - feature-gates=AllBeta=false
  - feature-gates=DisableCloudProviders=true
  - feature-gates=DisableKubeletCloudCredentialProviders=true
  - leader-elect=false
  - configure-cloud-routes=false
  - node-monitor-period=60s
  - concurrent-service-syncs=1
  - concurrent-deployment-syncs=1
  - concurrent-statefulset-syncs=1
  - concurrent-endpoint-syncs=1
  - concurrent-service-endpoint-syncs=1
  - mirroring-concurrent-service-endpoint-syncs=1
  - concurrent-ephemeralvolume-syncs=1
  - concurrent-gc-syncs=1
  - concurrent-horizontal-pod-autoscaler-syncs=1
  - concurrent-namespace-syncs=1
  - concurrent-replicaset-syncs=1
  - concurrent_rc_syncs=1
  - concurrent-resource-quota-syncs=1
  - concurrent-serviceaccount-token-syncs=1
  - concurrent-ttl-after-finished-syncs=1
  - node-monitor-grace-period=30m
kube-scheduler-arg:
  - log-flush-frequency=25s
  - profiling=false
  - leader-elect=false
  - feature-gates=AllAlpha=false
  - feature-gates=AllBeta=false
kubelet-arg:
  - feature-gates=AllAlpha=false
  - feature-gates=AllBeta=false
  - log-flush-frequency=25s
kube-proxy-arg:
  - log-flush-frequency=25s
kube-cloud-controller-arg:
  - log-flush-frequency=25s
